<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="4">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1190" startPos="568" endPos="568" selMode="0" offset="0" wrapCount="1" lang="C" encoding="-1" userReadOnly="no" filename="D:\UniversityOfMiskolc\University\2020_21_2\40.c" backupFilePath="" originalFileLastModifTimestamp="1174113942" originalFileLastModifTimestampHigh="30877478" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="966" startPos="513" endPos="513" selMode="0" offset="0" wrapCount="1" lang="C" encoding="-1" userReadOnly="no" filename="D:\UniversityOfMiskolc\University\2020_21_2\OS\Gyak7\openclose.c" backupFilePath="" originalFileLastModifTimestamp="1949031410" originalFileLastModifTimestampHigh="30880258" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1008" startPos="237" endPos="237" selMode="0" offset="0" wrapCount="1" lang="C" encoding="-1" userReadOnly="no" filename="D:\UniversityOfMiskolc\University\2020_21_2\OS\gyak9\O2IXLBunnamed.c" backupFilePath="" originalFileLastModifTimestamp="1671813099" originalFileLastModifTimestampHigh="30880278" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="30" xOffset="0" scrollWidth="840" startPos="1125" endPos="1125" selMode="0" offset="0" wrapCount="1" lang="C" encoding="-1" userReadOnly="no" filename="D:\UniversityOfMiskolc\University\2020_21_2\OS\gyak9\O2IXLBnamed.c" backupFilePath="" originalFileLastModifTimestamp="-1843572785" originalFileLastModifTimestampHigh="30880278" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="644" startPos="384" endPos="384" selMode="0" offset="0" wrapCount="1" lang="Normal Text" encoding="-1" userReadOnly="no" filename="D:\UniversityOfMiskolc\University\2020_21_2\OS\gyak9\O.txt" backupFilePath="" originalFileLastModifTimestamp="-1393327902" originalFileLastModifTimestampHigh="30880278" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="-16777216" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
